2024-06-12 17:51:18,301 INFO    MainThread:45763 [wandb_setup.py:_flush():76] Current SDK version is 0.17.1
2024-06-12 17:51:18,301 INFO    MainThread:45763 [wandb_setup.py:_flush():76] Configure stats pid to 45763
2024-06-12 17:51:18,301 INFO    MainThread:45763 [wandb_setup.py:_flush():76] Loading settings from /Users/filippomerlo/.config/wandb/settings
2024-06-12 17:51:18,301 INFO    MainThread:45763 [wandb_setup.py:_flush():76] Loading settings from /Users/filippomerlo/Documents/GitHub/SceneREG_project/code/dataset/wandb/settings
2024-06-12 17:51:18,301 INFO    MainThread:45763 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-06-12 17:51:18,301 INFO    MainThread:45763 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-06-12 17:51:18,301 INFO    MainThread:45763 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'code/dataset/dataset.py', 'program_abspath': '/Users/filippomerlo/Documents/GitHub/SceneREG_project/code/dataset/dataset.py', 'program': '/Users/filippomerlo/Documents/GitHub/SceneREG_project/code/dataset/dataset.py'}
2024-06-12 17:51:18,301 INFO    MainThread:45763 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-06-12 17:51:18,301 INFO    MainThread:45763 [wandb_init.py:_log_setup():520] Logging user logs to /Users/filippomerlo/Documents/GitHub/SceneREG_project/code/dataset/wandb/run-20240612_175118-16gt6ig2/logs/debug.log
2024-06-12 17:51:18,301 INFO    MainThread:45763 [wandb_init.py:_log_setup():521] Logging internal logs to /Users/filippomerlo/Documents/GitHub/SceneREG_project/code/dataset/wandb/run-20240612_175118-16gt6ig2/logs/debug-internal.log
2024-06-12 17:51:18,302 INFO    MainThread:45763 [wandb_init.py:_jupyter_setup():466] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x11f8c4040>
2024-06-12 17:51:18,302 INFO    MainThread:45763 [wandb_init.py:init():560] calling init triggers
2024-06-12 17:51:18,302 INFO    MainThread:45763 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {}
2024-06-12 17:51:18,302 INFO    MainThread:45763 [wandb_init.py:init():610] starting backend
2024-06-12 17:51:18,302 INFO    MainThread:45763 [wandb_init.py:init():614] setting up manager
2024-06-12 17:51:18,304 INFO    MainThread:45763 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-06-12 17:51:18,306 INFO    MainThread:45763 [wandb_init.py:init():622] backend started and connected
2024-06-12 17:51:18,312 INFO    MainThread:45763 [wandb_run.py:_label_probe_notebook():1334] probe notebook
2024-06-12 17:51:18,312 INFO    MainThread:45763 [wandb_run.py:_label_probe_notebook():1344] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-06-12 17:51:18,312 INFO    MainThread:45763 [wandb_init.py:init():711] updated telemetry
2024-06-12 17:51:18,328 INFO    MainThread:45763 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2024-06-12 17:51:18,759 INFO    MainThread:45763 [wandb_run.py:_on_init():2402] communicating current version
2024-06-12 17:51:18,838 INFO    MainThread:45763 [wandb_run.py:_on_init():2411] got version response 
2024-06-12 17:51:18,838 INFO    MainThread:45763 [wandb_init.py:init():795] starting run threads in backend
2024-06-12 17:51:21,576 WARNING MainThread:45763 [wandb_init.py:init():1175] interrupted
Traceback (most recent call last):
  File "/Users/filippomerlo/miniconda3/envs/torch/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1171, in init
    return wi.init()
  File "/Users/filippomerlo/miniconda3/envs/torch/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 808, in init
    run_start_result = run_start_handle.wait(timeout=30)
  File "/Users/filippomerlo/miniconda3/envs/torch/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "/Users/filippomerlo/miniconda3/envs/torch/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/Users/filippomerlo/miniconda3/envs/torch/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
  File "/Users/filippomerlo/miniconda3/envs/torch/lib/python3.10/threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "/Users/filippomerlo/miniconda3/envs/torch/lib/python3.10/threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2024-06-12 17:51:26,750 INFO    MainThread:45763 [wandb_settings.py:_apply_login():1911] Applying login settings: {}
2024-06-12 17:51:26,768 INFO    MainThread:45763 [wandb_setup.py:_flush():76] Current SDK version is 0.17.1
2024-06-12 17:51:26,768 INFO    MainThread:45763 [wandb_setup.py:_flush():76] Configure stats pid to 45763
2024-06-12 17:51:26,768 INFO    MainThread:45763 [wandb_setup.py:_flush():76] Loading settings from /Users/filippomerlo/.config/wandb/settings
2024-06-12 17:51:26,768 INFO    MainThread:45763 [wandb_setup.py:_flush():76] Loading settings from /Users/filippomerlo/Documents/GitHub/SceneREG_project/code/dataset/wandb/settings
2024-06-12 17:51:26,768 INFO    MainThread:45763 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-06-12 17:51:26,769 INFO    MainThread:45763 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-06-12 17:51:26,769 INFO    MainThread:45763 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'code/dataset/dataset.py', 'program_abspath': '/Users/filippomerlo/Documents/GitHub/SceneREG_project/code/dataset/dataset.py', 'program': '/Users/filippomerlo/Documents/GitHub/SceneREG_project/code/dataset/dataset.py'}
2024-06-12 17:51:26,769 INFO    MainThread:45763 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-06-12 17:51:26,769 INFO    MainThread:45763 [wandb_init.py:_log_setup():520] Logging user logs to /Users/filippomerlo/Documents/GitHub/SceneREG_project/code/dataset/wandb/run-20240612_175126-03ngt4lj/logs/debug.log
2024-06-12 17:51:26,769 INFO    MainThread:45763 [wandb_init.py:_log_setup():521] Logging internal logs to /Users/filippomerlo/Documents/GitHub/SceneREG_project/code/dataset/wandb/run-20240612_175126-03ngt4lj/logs/debug-internal.log
2024-06-12 17:51:26,769 INFO    MainThread:45763 [wandb_init.py:init():560] calling init triggers
2024-06-12 17:51:26,769 INFO    MainThread:45763 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {}
2024-06-12 17:51:26,769 INFO    MainThread:45763 [wandb_init.py:init():610] starting backend
2024-06-12 17:51:26,769 INFO    MainThread:45763 [wandb_init.py:init():614] setting up manager
2024-06-12 17:51:26,770 INFO    MainThread:45763 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-06-12 17:51:26,771 INFO    MainThread:45763 [wandb_init.py:init():622] backend started and connected
2024-06-12 17:51:26,778 INFO    MainThread:45763 [wandb_run.py:_label_probe_notebook():1334] probe notebook
2024-06-12 17:51:26,778 INFO    MainThread:45763 [wandb_run.py:_label_probe_notebook():1344] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-06-12 17:51:26,778 INFO    MainThread:45763 [wandb_init.py:init():711] updated telemetry
2024-06-12 17:51:26,791 INFO    MainThread:45763 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2024-06-12 17:52:57,181 ERROR   MainThread:45763 [wandb_init.py:init():770] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-06-12 17:52:57,185 ERROR   MainThread:45763 [wandb_init.py:init():1181] error in wandb.init()
Traceback (most recent call last):
  File "/Users/filippomerlo/miniconda3/envs/torch/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1171, in init
    return wi.init()
  File "/Users/filippomerlo/miniconda3/envs/torch/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 776, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-06-12 17:54:01,833 INFO    MainThread:45763 [wandb_settings.py:_apply_login():1911] Applying login settings: {}
2024-06-12 17:54:01,858 INFO    MainThread:45763 [wandb_setup.py:_flush():76] Current SDK version is 0.17.1
2024-06-12 17:54:01,858 INFO    MainThread:45763 [wandb_setup.py:_flush():76] Configure stats pid to 45763
2024-06-12 17:54:01,858 INFO    MainThread:45763 [wandb_setup.py:_flush():76] Loading settings from /Users/filippomerlo/.config/wandb/settings
2024-06-12 17:54:01,859 INFO    MainThread:45763 [wandb_setup.py:_flush():76] Loading settings from /Users/filippomerlo/Documents/GitHub/SceneREG_project/code/dataset/wandb/settings
2024-06-12 17:54:01,859 INFO    MainThread:45763 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-06-12 17:54:01,859 INFO    MainThread:45763 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-06-12 17:54:01,859 INFO    MainThread:45763 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'code/dataset/dataset.py', 'program_abspath': '/Users/filippomerlo/Documents/GitHub/SceneREG_project/code/dataset/dataset.py', 'program': '/Users/filippomerlo/Documents/GitHub/SceneREG_project/code/dataset/dataset.py'}
2024-06-12 17:54:01,859 INFO    MainThread:45763 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-06-12 17:54:01,859 INFO    MainThread:45763 [wandb_init.py:_log_setup():520] Logging user logs to /Users/filippomerlo/Documents/GitHub/SceneREG_project/code/dataset/wandb/run-20240612_175401-uxhwshya/logs/debug.log
2024-06-12 17:54:01,859 INFO    MainThread:45763 [wandb_init.py:_log_setup():521] Logging internal logs to /Users/filippomerlo/Documents/GitHub/SceneREG_project/code/dataset/wandb/run-20240612_175401-uxhwshya/logs/debug-internal.log
2024-06-12 17:54:01,859 INFO    MainThread:45763 [wandb_init.py:init():560] calling init triggers
2024-06-12 17:54:01,859 INFO    MainThread:45763 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {}
2024-06-12 17:54:01,859 INFO    MainThread:45763 [wandb_init.py:init():610] starting backend
2024-06-12 17:54:01,859 INFO    MainThread:45763 [wandb_init.py:init():614] setting up manager
2024-06-12 17:54:01,861 INFO    MainThread:45763 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-06-12 17:54:01,862 INFO    MainThread:45763 [wandb_init.py:init():622] backend started and connected
2024-06-12 17:54:01,888 INFO    MainThread:45763 [wandb_run.py:_label_probe_notebook():1334] probe notebook
2024-06-12 17:54:01,888 INFO    MainThread:45763 [wandb_run.py:_label_probe_notebook():1344] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-06-12 17:54:01,888 INFO    MainThread:45763 [wandb_init.py:init():711] updated telemetry
2024-06-12 17:54:01,910 INFO    MainThread:45763 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2024-06-12 17:55:32,288 ERROR   MainThread:45763 [wandb_init.py:init():770] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-06-12 17:55:32,291 ERROR   MainThread:45763 [wandb_init.py:init():1181] error in wandb.init()
Traceback (most recent call last):
  File "/Users/filippomerlo/miniconda3/envs/torch/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1171, in init
    return wi.init()
  File "/Users/filippomerlo/miniconda3/envs/torch/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 776, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
